//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamousPeopleFromAdygea.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamousHumanToUser
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdFamousPeople { get; set; }
    
        public virtual FamousHuman FamousHuman { get; set; }
        public virtual User User { get; set; }
    }
}
